/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/ground.glb -o src/components/Ground.jsx -r public -k 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Ground(props) {
  const { nodes, materials } = useGLTF("/models/ground.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Ground"
        geometry={nodes.Ground.geometry}
        material={materials.ground}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/ground.glb");
