/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/ground.glb -o src/components/Ground.jsx -r public -k 
*/

import React, { useRef, useMemo } from "react";
import { useGLTF } from "@react-three/drei";

export function Ground(props) {
  const { scene, nodes, materials } = useGLTF("/models/ground.glb");
  useMemo(() => {
    scene.traverse((object) => {
      if (object.isMesh) {
        object.castShadow = true;
        object.receiveShadow = true;
      }
    });
  }, [scene]);
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Landscape"
        geometry={nodes.Landscape.geometry}
        material={materials.ground}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/ground.glb");
