/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/willow.glb -o src/components/Willow.jsx -r public -k 
Author: EmreAlkan (https://sketchfab.com/Anadolubebesi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/willow-tree-2378d616b9da4ba39b5ccbe157e22e86
Title: Willow Tree
*/

import React, { useRef, useMemo } from "react";
import { useGLTF } from "@react-three/drei";

export function Willow(props) {
  const { scene, nodes, materials } = useGLTF("/models/willow.glb");
  useMemo(() => {
    scene.traverse((object) => {
      if (object.isMesh) {
        object.castShadow = true;
        object.receiveShadow = true;
      }
    });
  }, [scene]);
  return (
    <group {...props} dispose={null}>
      <group name="a29d8c7d8d40462d8808967e772b0766fbx" scale={0.01}>
        <group name="tree" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            name="tree_Malzeme010_0"
            geometry={nodes.tree_Malzeme010_0.geometry}
            material={materials["Malzeme.010"]}
          />
          <mesh
            name="tree_Malzeme010_0_1"
            geometry={nodes.tree_Malzeme010_0_1.geometry}
            material={materials["Malzeme.010"]}
          />
          <mesh
            name="tree_Malzeme010_0_2"
            geometry={nodes.tree_Malzeme010_0_2.geometry}
            material={materials["Malzeme.010"]}
          />
          <mesh
            name="leaves_Malzeme009_0"
            geometry={nodes.leaves_Malzeme009_0.geometry}
            material={materials["Malzeme.009"]}
          />
          <mesh
            name="leaves_Malzeme009_0_1"
            geometry={nodes.leaves_Malzeme009_0_1.geometry}
            material={materials["Malzeme.009"]}
          />
          <mesh
            name="leaves_Malzeme009_0_2"
            geometry={nodes.leaves_Malzeme009_0_2.geometry}
            material={materials["Malzeme.009"]}
          />
          <mesh
            name="leaves_Malzeme009_0_3"
            geometry={nodes.leaves_Malzeme009_0_3.geometry}
            material={materials["Malzeme.009"]}
          />
          <mesh
            name="leaves_Malzeme009_0_4"
            geometry={nodes.leaves_Malzeme009_0_4.geometry}
            material={materials["Malzeme.009"]}
          />
          <mesh
            name="leaves_Malzeme009_0_5"
            geometry={nodes.leaves_Malzeme009_0_5.geometry}
            material={materials["Malzeme.009"]}
          />
          <mesh
            name="leaves_Malzeme009_0_6"
            geometry={nodes.leaves_Malzeme009_0_6.geometry}
            material={materials["Malzeme.009"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/willow.glb");
